alias ls="exa"
alias l="ll -a"
alias px="proxychains4"
alias code="/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code"
alias set_proxy="export https_proxy=\"http://127.0.0.1:1087\";export http_proxy=\"http://127.0.0.1:1087\";export all_proxy=\"socks5://127.0.0.1:1087\""
alias empty_proxy="export http_proxy=;export https_proxy=;export all_proxy="
